# Generated by Django 4.2.2 on 2024-01-27 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_alter_orderupdates_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdates',
            name='orders',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_updates', to='ecommerceapp.order'),
        ),
    ]
